'use strict';


// POKEMONS //

/** @type {import('sequelize-cli').Migration} */
module.exports = {
   up:(queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('pokemons', [
      {
        id: 1,
        name: 'Bulbasaur',
        weight: 6,
        height: 70,
        description: 'There is a plant seed on its back right from the day this Pokémon is born, The seed slowly grows larger.',
        hp: 45,
        atk: 49,
        def: 49,
        satk: 65,
        sdef: 65,
        spd: 45,
        price: 1200,
      },
      {
        id: 4,
        name: 'Charmander',
        weight: 8,
        height: 60,
        description: 'It has a preference for hot things. When it rains, steam is said to sput from the tip of its tail',
        hp: 39,
        atk: 52,
        def: 43,
        satk: 60,
        sdef: 50,
        spd: 65,
        price: 1500,
        },
      {
          id: 7,
          name: 'Squirtle',
          weight: 9,
          height: 50,
          description: 'When it retracts its long neck into its shell, it squirts out water with vigorous force',
          hp: 44,
          atk: 48,
          def: 65,
          satk: 50,
          sdef: 64,
          spd: 43,
          price: 1300,
      },
      {
        id: 12,
        name: 'Butterfree',
        weight: 32,
        height: 110,
        description: 'In battle, it flaps its wings at great speed to release highly toxic dust into the air.',
        hp: 60,
        atk: 45,
        def: 50,
        satk: 90,
        sdef: 80,
        spd: 70,
        price: 1200,
      },
      {
        id: 25,
        name: 'Pikachu',
        weight: 6,
        height: 40,
        description: 'Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.',
        hp: 45,
        atk: 49,
        def: 49,
        satk: 65,
        sdef: 65,
        spd: 45,
        price: 1200,
      },
      {
        id: 152,
        name: 'Mew',
        weight: 4,
        height: 40,
        description: "When view through a microscope this Pokemon's short, fine, delicate hair can be seen.",
        hp: 100,
        atk: 100,
        def: 100,
        satk: 100,
        sdef: 100,
        spd: 100,
        price: 5000,
      },
      {
        id: 92,
        name: 'Gastly',
        weight: 1,
        height: 130,
        description: "Born from gases, anyone would faint if engulfed by it's gaseous body, which contains poison.",
        hp: 30,
        atk: 35,
        def: 30,
        satk: 100,
        sdef: 35,
        spd: 80,
        price: 1400,
      },
      {
        id: 132,
        name: 'Ditto',
        weight: 4,
        height: 30,
        description: "It can reconstitute it's entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",
        hp: 48,
        atk: 48,
        def: 48,
        satk: 48,
        sdef: 48,
        spd: 48,
        price: 1300,
      },
      {
        id: 304,
        name: 'Aron',
        weight: 6,
        height: 40,
        description: "It eats iron ore - and sometimes railroad tracks - to build up the steel armor that protects it's body.",
        hp: 45,
        atk: 49,
        def: 49,
        satk: 65,
        sdef: 65,
        spd: 45,
        price: 1200,
      },
          
      ]);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('pokemons', null, {});
  },
};
