'use strict';


// POKEMONS //

/** @type {import('sequelize-cli').Migration} */
module.exports = {
   up:(queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('pokemons', [
      {
        id: 1,
        name: 'Bulbasaur',
        weight: 6.9,
        height: 0.7,
        description: 'There is a plant seed on its back right from the day this Pokémon is born, The seed slowly grows larger.',
        hp: 45,
        atk: 49,
        def: 49,
        satk: 65,
        sdef: 65,
        spd: 45,
        price: 1200,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png",
      },
      {
        id: 4,
        name: 'Charmander',
        weight: 8.5,
        height: 0.6,
        description: 'It has a preference for hot things. When it rains, steam is said to sput from the tip of its tail',
        hp: 39,
        atk: 52,
        def: 43,
        satk: 60,
        sdef: 50,
        spd: 65,
        price: 1500,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png",
        },
      {
          id: 7,
          name: 'Squirtle',
          weight: 9.0,
          height: 0.5,
          description: 'When it retracts its long neck into its shell, it squirts out water with vigorous force',
          hp: 44,
          atk: 48,
          def: 65,
          satk: 50,
          sdef: 64,
          spd: 43,
          price: 1300,
          pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png",
      },
      {
        id: 12,
        name: 'Butterfree',
        weight: 32,
        height: 1.1,
        description: 'In battle, it flaps its wings at great speed to release highly toxic dust into the air.',
        hp: 60,
        atk: 45,
        def: 50,
        satk: 90,
        sdef: 80,
        spd: 70,
        price: 1200,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png",
      },
      {
        id: 25,
        name: 'Pikachu',
        weight: 6.0,
        height: 0.4,
        description: 'Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.',
        hp: 45,
        atk: 49,
        def: 49,
        satk: 65,
        sdef: 65,
        spd: 45,
        price: 1200,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/025.png",
      },
      {
        id: 151,
        name: 'Mew',
        weight: 4.0,
        height: 0.4,
        description: "When view through a microscope this Pokemon's short, fine, delicate hair can be seen.",
        hp: 100,
        atk: 100,
        def: 100,
        satk: 100,
        sdef: 100,
        spd: 100,
        price: 5000,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png",
      },
      {
        id: 92,
        name: 'Gastly',
        weight: 0.1,
        height: 1.3,
        description: "Born from gases, anyone would faint if engulfed by it's gaseous body, which contains poison.",
        hp: 30,
        atk: 35,
        def: 30,
        satk: 100,
        sdef: 35,
        spd: 80,
        price: 1400,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/092.png",
      },
      {
        id: 132,
        name: 'Ditto',
        weight: 4.0,
        height: 30,
        description: "It can reconstitute it's entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",
        hp: 48,
        atk: 48,
        def: 48,
        satk: 48,
        sdef: 48,
        spd: 48,
        price: 1300,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/132.png",
      },
      {
        id: 304,
        name: 'Aron',
        weight: 60.0,
        height: 0.4,
        description: "Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.",
        hp: 78,
        atk: 84,
        def: 78,
        satk: 109,
        sdef: 85,
        spd: 100,
        price: 1200,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/304.png",
      },
      {
        id: 5,
        name: 'Charmeleon',
        weight: 19.0,
        height: 1.1,
        description: "It has a barbaric nature. In battle, it whips its fiery tail around and slashes away with sharp claws.",
        hp: 58,
        atk: 64,
        def: 58,
        satk: 80,
        sdef: 65,
        spd: 80,
        price: 1600,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png",
      },
      
      {
        id: 6,
        name: 'Charizard',
        weight: 90.5,
        height: 1.7,
        description: "It eats iron ore - and sometimes railroad tracks - to build up the steel armor that protects it's body.",
        hp: 78,
        atk: 84,
        def: 78,
        satk: 109,
        sdef: 85,
        spd: 100,
        price: 2000,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png",
      },
     
      {
        id: 8,
        name: 'Wartortle',
        weight: 22.5,
        height: 1.0,
        description: "It is recognized as a symbol of longevity. If its shell has algae on it, that Wartortle is very old.",
        hp: 59,
        atk: 63,
        def: 80,
        satk: 65,
        sdef: 80,
        spd: 58,
        price: 1400,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png",
      },
      {
        id: 9,
        name: 'Blastoise',
        weight: 85.5,
        height: 1.6,
        description: "It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.",
        hp: 79,
        atk: 83,
        def: 100,
        satk: 85,
        sdef: 105,
        spd: 78,
        price: 2000,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png",
      },
      {
        id: 2,
        name: 'Ivysaur ',
        weight: 1.0,
        height: 13.0,
        description: "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
        hp: 59,
        atk: 63,
        def: 80,
        satk: 65,
        sdef: 80,
        spd: 58,
        price: 1400,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png",
      },
      {
        id: 3,
        name: 'Venusaur ',
        weight: 100.0,
        height: 2.0,
        description: "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
        hp: 78,
        atk: 84,
        def: 78,
        satk: 100,
        sdef: 100,
        spd: 100,
        price: 2000,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png",
      },
      {
        id: 94,
        name: 'Gengar',
        weight: 40.5,
        height: 1.5,
        description: "On the night of a full moon, if shadows move on their own and laugh, it must be Gengar’s doing.",
        hp: 78,
        atk: 84,
        def: 78,
        satk: 100,
        sdef: 100,
        spd: 100,
        price: 2200,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/094.png",
      },
      {
        id: 26,
        name: 'Raichu ',
        weight: 0.8,
        height: 30.0,
        description: "Its long tail serves as a ground to protect itself from its own high-voltage power.",
        hp: 78,
        atk: 84,
        def: 78,
        satk: 100,
        sdef: 100,
        spd: 100,
        price: 1800,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/026.png",
      },
      {
        id: 149,
        name: 'Dragonite',
        weight: 210.0,
        height: 2.2,
        description: "It’s a kindhearted Pokémon. If it spots a drowning person or Pokémon, Dragonite simply must help them.",
        hp: 60,
        atk: 90,
        def: 55,
        satk: 90,
        sdef: 80,
        spd: 110,
        price: 2100,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/149.png",
      },
      {
        id: 24,
        name: 'Arbok',
        weight: 210.0,
        height: 2.2,
        description: "The frightening patterns on its belly have been studied. Six variations have been confirmed",
        hp: 60,
        atk: 90,
        def: 55,
        satk: 90,
        sdef: 80,
        spd: 110,
        price: 2100,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/024.png",
      },
      {
        id: 77,
        name: 'Ponyta',
        weight: 210.0,
        height: 2.2,
        description: "While young, it has six gorgeous tails. When it grows, several new tails are sprouted.",  
        hp: 60,
        atk: 90,
        def: 55,
        satk: 90,
        sdef: 80,
        spd: 110,
        price: 2100,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/077.png",
      },
      {
        id: 52,
        name: 'Meowth',
        weight: 210.0,
        height: 2.2,
        description: "It loves to collect shiny things. If it’s in a good mood, it might even let its Trainer have a look at its hoard of treasures",
        hp: 60,
        atk: 90,
        def: 55,
        satk: 90,
        sdef: 80,
        spd: 110,
        price: 2100,
        pokeurl: "https://assets.pokemon.com/assets/cms2/img/pokedex/full/052.png",
      },
       
      ]);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('pokemons', null, {});
  },
};
